//$file${.::main.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: sem.qm
// File:  ${.::main.cpp}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::main.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"             // QP/C++ real-time embedded framework
#include <iostream>

extern "C" {
//............................................................................
void Q_onError(char const * const module, int id) {std::cerr << "Assertion failed in " << module << ':' << id << std::endl;exit(-1);}
void assert_failed(char const * const module, int_t const id); // prototype
void assert_failed(char const * const module, int_t const id) {Q_onError(module, id);}
} // extern "C"

namespace QP {
void QF::onStartup  (    ) {QF::consoleSetup();}
void QF::onCleanup  (void) {QF::consoleCleanup();}
void QF::onClockTick(void) {QTimeEvt::TICK_X(0U, nullptr);}  // QTimeEvt clock tick processing
} // namespace QP

enum AppSignals : std::uint32_t {
   TOUT_SIG = QP::Q_USER_SIG,
};

enum colorTime : std::uint32_t {
 COLOR_R_TIME = 100,
};

#define PRINT(str) std::cout << str << std::endl;

//$declare${AOs::Traffic} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Traffic} ............................................................
class Traffic : public QP::QActive {
public:
    static Traffic inst;
    QP::QTimeEvt colorTimeEvt;

public:
    Traffic();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(YtoG);
    Q_STATE_DECL(G);
    Q_STATE_DECL(YtoR);
    Q_STATE_DECL(R);
}; // class Traffic

} // namespace APP
//$enddecl${AOs::Traffic} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Traffic} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Traffic} ............................................................
Traffic Traffic::inst;

//${AOs::Traffic::Traffic} ...................................................
Traffic::Traffic()
: QActive(Q_STATE_CAST(&Traffic::initial)),
colorTimeEvt(this, TOUT_SIG,0)
{}

//${AOs::Traffic::SM} ........................................................
Q_STATE_DEF(Traffic, initial) {
    //${AOs::Traffic::SM::initial}
    std::cout << "init" << std::endl;
    APP::Traffic::inst.colorTimeEvt.armX(COLOR_R_TIME, COLOR_R_TIME);
    (void)e; // unused parameter

    QS_FUN_DICTIONARY(&Traffic::YtoG);
    QS_FUN_DICTIONARY(&Traffic::G);
    QS_FUN_DICTIONARY(&Traffic::YtoR);
    QS_FUN_DICTIONARY(&Traffic::R);

    return tran(&R);
}

//${AOs::Traffic::SM::YtoG} ..................................................
Q_STATE_DEF(Traffic, YtoG) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::YtoG}
        case Q_ENTRY_SIG: {
            PRINT("YtoG");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::YtoG::TOUT}
        case TOUT_SIG: {
            status_ = tran(&G);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Traffic::SM::G} .....................................................
Q_STATE_DEF(Traffic, G) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::G}
        case Q_ENTRY_SIG: {
            PRINT("G");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::G::TOUT}
        case TOUT_SIG: {
            status_ = tran(&YtoR);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Traffic::SM::YtoR} ..................................................
Q_STATE_DEF(Traffic, YtoR) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::YtoR}
        case Q_ENTRY_SIG: {
            PRINT("YtoR");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::YtoR::TOUT}
        case TOUT_SIG: {
            status_ = tran(&R);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Traffic::SM::R} .....................................................
Q_STATE_DEF(Traffic, R) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::R}
        case Q_ENTRY_SIG: {
            PRINT("R");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::R::TOUT}
        case TOUT_SIG: {
            status_ = tran(&YtoG);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

} // namespace APP
//$enddef${AOs::Traffic} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

int main()
{
    QP::QF::init();  // initialize the framework and the underlying RT kernel

    QP::QEvt const *trafficQueueSto[10];
    APP::Traffic::inst.start(
        1U,                          // QP prio. of the AO
        trafficQueueSto,             // event queue storage
        Q_DIM(trafficQueueSto),      // queue length [events]
        nullptr, 0U);                // no stack storage

    return QP::QF::run(); // run the QF application
}
