//$file${.::main.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: sem.qm
// File:  ${.::main.cpp}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::main.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"             // QP/C++ real-time embedded framework
#include <iostream>

extern "C" {
//............................................................................
void Q_onError(char const * const module, int id) {std::cerr << "Assertion failed in " << module << ':' << id << std::endl;exit(-1);}
void assert_failed(char const * const module, int_t const id); // prototype
void assert_failed(char const * const module, int_t const id) {Q_onError(module, id);}
} // extern "C"

namespace QP {
void QF::onStartup  (    ) {QF::consoleSetup();}
void QF::onCleanup  (void) {QF::consoleCleanup();}
void QF::onClockTick(void) {QTimeEvt::TICK_X(0U, nullptr);}  // QTimeEvt clock tick processing
} // namespace QP

constexpr std::uint32_t TICKS_PER_SEC {100U};

//$declare${AOs::Led} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Led} ................................................................
class Led {
public:
    void ledOn(std::string color);
    void ledOff(std::string color);
}; // class Led

} // namespace APP
//$enddecl${AOs::Led} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::Sem} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Sem} ................................................................
class Sem : public QP::QActive {
private:
    QP::QTimeEvt m_timeEvt;

public:
    static Sem inst;
    APP::Led* ledInst;

public:
    Sem();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(R);
    Q_STATE_DECL(YtoG);
    Q_STATE_DECL(G);
    Q_STATE_DECL(YtoR);
}; // class Sem

} // namespace APP
//$enddecl${AOs::Sem} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${Shared::AppSignals} ......................................................
enum AppSignals : QP::QSignal {
    TIMEOUT_SIG = QP::Q_USER_SIG, // published by Table to let a Philo eat

   MAX_SIG         // the last signal
};

//${Shared::AO_Sem} ..........................................................
extern QP::QActive * const AO_Sem;

//${Shared::ledInst33} .......................................................
extern APP::Led ledInst33;

} // namespace APP
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${Shared::AO_Sem} ..........................................................
QP::QActive * const AO_Sem = &Sem::inst;

//${Shared::ledInst33} .......................................................
APP::Led ledInst33;

} // namespace APP
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Led} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Led} ................................................................

//${AOs::Led::ledOn} .........................................................
void Led::ledOn(std::string color) {
    std::cout << "Led " << color << " On" << std::endl;
}

//${AOs::Led::ledOff} ........................................................
void Led::ledOff(std::string color) {
    std::cout << "Led " << color << " Off" << std::endl;
}

} // namespace APP
//$enddef${AOs::Led} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Sem} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Sem} ................................................................
Sem Sem::inst;

//${AOs::Sem::Sem} ...........................................................
Sem::Sem()
: QActive(Q_STATE_CAST(&Sem::initial)),
    m_timeEvt(this, TIMEOUT_SIG, 0U)
{
    inst.ledInst = &APP::ledInst33;
    std::cout << "ledinst " << inst.ledInst << std::endl;
}

//${AOs::Sem::SM} ............................................................
Q_STATE_DEF(Sem, initial) {
    //${AOs::Sem::SM::initial}
    m_timeEvt.armX(TICKS_PER_SEC/2, TICKS_PER_SEC/2);
    (void)e; // unused parameter

    QS_FUN_DICTIONARY(&Sem::R);
    QS_FUN_DICTIONARY(&Sem::YtoG);
    QS_FUN_DICTIONARY(&Sem::G);
    QS_FUN_DICTIONARY(&Sem::YtoR);

    return tran(&R);
}

//${AOs::Sem::SM::R} .........................................................
Q_STATE_DEF(Sem, R) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sem::SM::R}
        case Q_ENTRY_SIG: {
            inst.ledInst->ledOff("R");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sem::SM::R::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&YtoG);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Sem::SM::YtoG} ......................................................
Q_STATE_DEF(Sem, YtoG) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sem::SM::YtoG}
        case Q_ENTRY_SIG: {
            inst.ledInst->ledOn("YtoG");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sem::SM::YtoG::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&G);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Sem::SM::G} .........................................................
Q_STATE_DEF(Sem, G) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sem::SM::G}
        case Q_ENTRY_SIG: {
            inst.ledInst->ledOn("G");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sem::SM::G::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&YtoR);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Sem::SM::YtoR} ......................................................
Q_STATE_DEF(Sem, YtoR) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sem::SM::YtoR}
        case Q_ENTRY_SIG: {
            inst.ledInst->ledOn("YtoR");
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sem::SM::YtoR::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&R);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

} // namespace APP
//$enddef${AOs::Sem} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

int main()
{
    QP::QF::init();  // initialize the framework and the underlying RT kernel

    QP::QEvt const *semQueueSto[10];
    APP::AO_Sem->start(
        1U,                          // QP prio. of the AO
        semQueueSto,              // event queue storage
        Q_DIM(semQueueSto),       // queue length [events]
        nullptr, 0U);                // no stack storage


    return QP::QF::run(); // run the QF application
}
