//$file${.::main.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: sem.qm
// File:  ${.::main.cpp}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::main.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"             // QP/C++ real-time embedded framework
#include <iostream>

extern "C" {
//............................................................................
void Q_onError(char const * const module, int id) {std::cerr << "Assertion failed in " << module << ':' << id << std::endl;exit(-1);}
void assert_failed(char const * const module, int_t const id); // prototype
void assert_failed(char const * const module, int_t const id) {Q_onError(module, id);}
} // extern "C"

namespace QP {
void QF::onStartup  (    ) {QF::consoleSetup();}
void QF::onCleanup  (void) {QF::consoleCleanup();}
void QF::onClockTick(void) {QTimeEvt::TICK_X(0U, nullptr);}  // QTimeEvt clock tick processing
} // namespace QP

enum colorTimers : uint32_t {
    COLOR_R_TIME = 500,
    COLOR_Y_TIME = 200,
    COLOR_G_TIME = 3000,
    PRINT_TIME = 100,
    PULL_TIME = 10,

};

enum AppSignals : uint32_t {
  TOUT_SIG = QP::Q_USER_SIG,
PRINT_SIG,
BUTTON_SIG,
};

#define PRINT(str) std::cout << str << std::endl;
#define REARM(time) APP::Traffic::inst.colorTimeEvt.rearm(time);
#define PRINT_CTR()  std::cout << APP::Traffic::inst.colorTimeEvt.getCtr()/100 << std::endl


//$declare${AOs::Led} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Led} ................................................................
class Led {
public:
    void ledOn(std::string color);
}; // class Led

} // namespace APP
//$enddecl${AOs::Led} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::LedR} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::LedR} ...............................................................
class LedR : public APP::Led {
public:
    static LedR inst;

public:
    void on();
}; // class LedR

} // namespace APP
//$enddecl${AOs::LedR} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::LedY} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::LedY} ...............................................................
class LedY : public APP::Led {
public:
    static LedY inst;

public:
    void on();
}; // class LedY

} // namespace APP
//$enddecl${AOs::LedY} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::LedG} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::LedG} ...............................................................
class LedG : public APP::Led {
public:
    static LedG inst;

public:
    void on();
}; // class LedG

} // namespace APP
//$enddecl${AOs::LedG} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::Traffic} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Traffic} ............................................................
class Traffic : public QP::QActive {
public:
    static Traffic inst;
    QP::QTimeEvt colorTimeEvt;
    QP::QTimeEvt printTimeEvt;
    APP::LedR* ledR=&APP::LedR::inst;
    APP::LedY* ledY=&APP::LedY::inst;
    APP::LedG* ledG=&APP::LedG::inst;

public:
    Traffic();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(root);
    Q_STATE_DECL(YtoG);
    Q_STATE_DECL(YtoR);
    Q_STATE_DECL(G);
    Q_STATE_DECL(R);
}; // class Traffic

} // namespace APP
//$enddecl${AOs::Traffic} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::Button} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Button} .............................................................
class Button : public QP::QActive {
public:
    QP::QTimeEvt pullTimeEvt;
    static Button inst;

public:
    Button();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(pulling);
}; // class Button

} // namespace APP
//$enddecl${AOs::Button} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Led} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Led} ................................................................

//${AOs::Led::ledOn} .........................................................
void Led::ledOn(std::string color) {
    PRINT(color);
}

} // namespace APP
//$enddef${AOs::Led} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::LedR} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::LedR} ...............................................................
LedR LedR::inst;

//${AOs::LedR::on} ...........................................................
void LedR::on() {
    ledOn("RR");
}

} // namespace APP
//$enddef${AOs::LedR} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::LedY} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::LedY} ...............................................................
LedY LedY::inst;

//${AOs::LedY::on} ...........................................................
void LedY::on() {
    ledOn("Y");
}

} // namespace APP
//$enddef${AOs::LedY} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::LedG} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::LedG} ...............................................................
LedG LedG::inst;

//${AOs::LedG::on} ...........................................................
void LedG::on() {
    ledOn("G");
}

} // namespace APP
//$enddef${AOs::LedG} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Traffic} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Traffic} ............................................................
Traffic Traffic::inst;

//${AOs::Traffic::Traffic} ...................................................
Traffic::Traffic()
: QActive(Q_STATE_CAST(&Traffic::initial)),
 colorTimeEvt(this, TOUT_SIG, 0U),
 printTimeEvt(this, PRINT_SIG, 0U)

{}

//${AOs::Traffic::SM} ........................................................
Q_STATE_DEF(Traffic, initial) {
    //${AOs::Traffic::SM::initial}
    std::cout << "init1" << std::endl;
    APP::Traffic::inst.colorTimeEvt.armX(COLOR_R_TIME,COLOR_R_TIME);
    APP::Traffic::inst.printTimeEvt.armX(PRINT_TIME,PRINT_TIME);

    (void)e; // unused parameter

    QS_FUN_DICTIONARY(&Traffic::root);
    QS_FUN_DICTIONARY(&Traffic::YtoG);
    QS_FUN_DICTIONARY(&Traffic::YtoR);
    QS_FUN_DICTIONARY(&Traffic::G);
    QS_FUN_DICTIONARY(&Traffic::R);

    return tran(&R);
}

//${AOs::Traffic::SM::root} ..................................................
Q_STATE_DEF(Traffic, root) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::root::PRINT}
        case PRINT_SIG: {
            PRINT_CTR();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::root::BUTTON}
        case BUTTON_SIG: {
            PRINT("button signal received");
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Traffic::SM::root::YtoG} ............................................
Q_STATE_DEF(Traffic, YtoG) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::root::YtoG}
        case Q_ENTRY_SIG: {
            APP::Traffic::inst.ledY->on();
            REARM(COLOR_Y_TIME);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::root::YtoG::TOUT}
        case TOUT_SIG: {
            status_ = tran(&G);
            break;
        }
        default: {
            status_ = super(&root);
            break;
        }
    }
    return status_;
}

//${AOs::Traffic::SM::root::YtoR} ............................................
Q_STATE_DEF(Traffic, YtoR) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::root::YtoR}
        case Q_ENTRY_SIG: {
            APP::Traffic::inst.ledY->on();
            REARM(COLOR_Y_TIME);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::root::YtoR::TOUT}
        case TOUT_SIG: {
            status_ = tran(&R);
            break;
        }
        default: {
            status_ = super(&root);
            break;
        }
    }
    return status_;
}

//${AOs::Traffic::SM::root::G} ...............................................
Q_STATE_DEF(Traffic, G) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::root::G}
        case Q_ENTRY_SIG: {
            APP::Traffic::inst.ledG->on();
            REARM(COLOR_G_TIME);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::root::G::TOUT}
        case TOUT_SIG: {
            status_ = tran(&YtoR);
            break;
        }
        default: {
            status_ = super(&root);
            break;
        }
    }
    return status_;
}

//${AOs::Traffic::SM::root::R} ...............................................
Q_STATE_DEF(Traffic, R) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Traffic::SM::root::R}
        case Q_ENTRY_SIG: {
            APP::Traffic::inst.ledR->on();
            REARM(COLOR_R_TIME);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Traffic::SM::root::R::TOUT}
        case TOUT_SIG: {
            status_ = tran(&YtoG);
            break;
        }
        default: {
            status_ = super(&root);
            break;
        }
    }
    return status_;
}

} // namespace APP
//$enddef${AOs::Traffic} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Button} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace APP {

//${AOs::Button} .............................................................
Button Button::inst;

//${AOs::Button::Button} .....................................................
Button::Button()
: QActive(Q_STATE_CAST(&Button::initial)),
 pullTimeEvt(this, TOUT_SIG, 0U)

{}

//${AOs::Button::SM} .........................................................
Q_STATE_DEF(Button, initial) {
    //${AOs::Button::SM::initial}
    PRINT("button init");
    APP::Button::inst.pullTimeEvt.armX(PULL_TIME,PULL_TIME);

    (void)e; // unused parameter
    return tran(&pulling);
}

//${AOs::Button::SM::pulling} ................................................
Q_STATE_DEF(Button, pulling) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Button::SM::pulling::TOUT}
        case TOUT_SIG: {
            switch (QP::QF::consoleGetKey()) {

              case ' ':
               {
                PRINT("space");
                static QP::QEvt evt(BUTTON_SIG);
                APP::Traffic::inst.POST(&evt,0);
               }
            break;
              default:
                break;
            };
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

} // namespace APP
//$enddef${AOs::Button} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

int main()
{
    QP::QF::init();  // initialize the framework and the underlying RT kernel

    QP::QEvt const *trafficQueueSto[10];
    APP::Traffic::inst.start(
        1U,                          // QP prio. of the AO
        trafficQueueSto,             // event queue storage
        Q_DIM(trafficQueueSto),      // queue length [events]
        nullptr, 0U);                // no stack storage


    QP::QEvt const *buttonQueueSto[10];
    APP::Button::inst.start(
        2U,                          // QP prio. of the AO
        buttonQueueSto,             // event queue storage
        Q_DIM(buttonQueueSto),      // queue length [events]
        nullptr, 0U);

    return QP::QF::run(); // run the QF application
}
