//$file${.::blinky.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blinky.qm
// File:  ${.::blinky.cpp}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::blinky.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"
#include "blinky.hpp"
#include <iostream>

enum BlinkySignals {
    TIMEOUT_SIG = QP::Q_USER_SIG,
    MAX_SIG
};

enum {
   BSP_TICKS_PER_SEC = 100
};

void BSP_ledOff(void)
{
    std::cout << "LED OFF" << std::endl;
}

void BSP_ledOn(void)
{
    std::cout << "LED ON" << std::endl;
}
void BSP_ledOff2(void)
{
    std::cout << "LED OFF2" << std::endl;
}

void BSP_ledOn2(void)
{
    std::cout << "LED ON2" << std::endl;
}

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpcpp version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky} .............................................................
Blinky Blinky::inst;

//${AOs::Blinky::Blinky} .....................................................
Blinky::Blinky()
: QMActive(Q_STATE_CAST(&Blinky::initial)),
    m_timeEvt(this, TIMEOUT_SIG, 0U)
{}

//${AOs::Blinky::SM} .........................................................
QM_STATE_DEF(Blinky, initial) {
    //${AOs::Blinky::SM::initial}
    m_timeEvt.armX(BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);
    (void)e; // unused parameter

    QS_FUN_DICTIONARY(&Blinky::off);
    QS_FUN_DICTIONARY(&Blinky::on);

    static struct {
        QP::QMState const *target;
        QP::QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &off_s, // target state
        {
            &off_e, // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return qm_tran_init(&tatbl_);
}

//${AOs::Blinky::SM::off} ....................................................
QP::QMState const Blinky::off_s = {
    QM_STATE_NULL, // superstate (top)
    &Blinky::off,
    &Blinky::off_e,
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::Blinky::SM::off}
QM_ACTION_DEF(Blinky, off_e) {
    BSP_ledOff();
    return qm_entry(&off_s);
}
//${AOs::Blinky::SM::off}
QM_STATE_DEF(Blinky, off) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::off::TIMEOUT}
        case TIMEOUT_SIG: {

            static struct {
                QP::QMState const *target;
                QP::QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &on_s, // target state
                {
                    &on_e, // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = qm_tran(&tatbl_);
            break;
        }
        default: {
            status_ = Q_RET_SUPER;
            break;
        }
    }
    return status_;
}

//${AOs::Blinky::SM::on} .....................................................
QP::QMState const Blinky::on_s = {
    QM_STATE_NULL, // superstate (top)
    &Blinky::on,
    &Blinky::on_e,
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::Blinky::SM::on}
QM_ACTION_DEF(Blinky, on_e) {
    BSP_ledOn();
    return qm_entry(&on_s);
}
//${AOs::Blinky::SM::on}
QM_STATE_DEF(Blinky, on) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::on::TIMEOUT}
        case TIMEOUT_SIG: {

            static struct {
                QP::QMState const *target;
                QP::QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &off_s, // target state
                {
                    &off_e, // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = qm_tran(&tatbl_);
            break;
        }
        default: {
            status_ = Q_RET_SUPER;
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Test} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Test} ...............................................................

//${AOs::Test::Test} .........................................................
Test::Test(std::uint8_t param1)
: QActive(Q_STATE_CAST(&Test::initial)),
    timer(this, TIMEOUT_SIG, 0U)
{}

//${AOs::Test::SM} ...........................................................
Q_STATE_DEF(Test, initial) {
    //${AOs::Test::SM::initial}
    timer.armX(100, 100);
    (void)e; // unused parameter
    return tran(&state1);
}

//${AOs::Test::SM::state1} ...................................................
Q_STATE_DEF(Test, state1) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Test::SM::state1}
        case Q_ENTRY_SIG: {
            BSP_ledOn2();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Test::SM::state1::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&state2);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Test::SM::state2} ...................................................
Q_STATE_DEF(Test, state2) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Test::SM::state2}
        case Q_ENTRY_SIG: {
            BSP_ledOff2();
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Test::SM::state2::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&state1);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Test} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
